DigiBoard/DigiBoard/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('dboard.urls')),
    
]

DigiBoard/dboard/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$',views.index,name='index'),
  	url(r'^history/$',views.SearchListView.as_view(),name='history'),
    
  	url(r'^accounts/',include('django.contrib.auth.urls')),
  	url(r'^search/create/$', views.NotificationCreateView.as_view(), name='create'),
    url(r'^/signup$', views.signup, name='signup'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DigiBoard/dboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save
from datetime import datetime, timedelta, time
today = datetime.now().date()
tomorrow = today + timedelta(1)
today_start = datetime.combine(today, time())
today_end = datetime.combine(tomorrow, time())


# Create your models here.

class Search(models.Model):
	user=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
	source = models.IntegerField()
	des = models.IntegerField()
	HH = models.IntegerField()
	MM = models.IntegerField()
	
	xm=models.IntegerField(null=True)
	am=models.IntegerField(null=True)
	bm=models.IntegerField(null=True)
	cm=models.IntegerField(null=True)
	dm=models.IntegerField(null=True)
	em=models.IntegerField(null=True)
	fm=models.IntegerField(null=True)
	gm=models.IntegerField(null=True)

	# timestamp=models.DateTimeField(auto_now=False,auto_now_add=True)
	# def __str__(self):
	# 	return str(self.source)

# class UserProfile(models.Model):
# 	user=models.OneToOneField(User)
# 	first_name=models.CharField(max_length=200)
# 	last_name=models.CharField(max_length=200)
# 	avatar=models.FileField(null=True,blank=True)

# 	class Meta:
# 		db_table='UserProfile'
# 		ordering=['user_id']

# 	def get_url(self):
# 		return reverse('user-detail',args=[str(self.id)])

# 	def __str__(self):
# 		return self.user.username

# def create_profile(sender, **kwargs):
# 	if kwargs['created']:
# 		user_profile=UserProfile.objects.create(user=kwargs['instance'])
# post_save.connect(create_profile,sender=User)

DigiBoard/dboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Search

class SignUpForm(UserCreationForm):
	class Meta:
		model=User
		fields=('username','first_name','last_name','password1','password2')

class SearchForm(forms.ModelForm):
    class Meta:
        model = Search
        fields = [
            "source",
            "des",
            "HH",
            "MM"
        ]

DigiBoard/dboard/views.py
from django.shortcuts import render
from .models import *
from django.views import generic
from django import forms
from .forms import SearchForm,SignUpForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render,redirect
from django.db.models import Q
import datetime

def td(i, f):
    if f.second>i.second:
        t=(f.first-i.first)*60+f.second-i.second
    else:
        t=(f.first-i.first-1)*60+60-(i.second-f.second)
    return t

class make_pair():
    def __init__(self, a, b):
        self.first = a
        self.second = b

# data = []
print("PRESS\nO FOR AMRITSAR\n1 FOR BATHINDA\n2 FOR CHANDIGARH\n3 FOR JALANDHAR\n4 FOR LUDHIANA\n5 FOR PATIALA\n6 FOR SANGRUR\n7 FOR PATHANKOT\n8 FOR FEROZEPUR\n9 FOR MOGA\n")
##make_pair(make_pair(7,11),make_pair(11,41))
###def fun(a, b, c):
    
    ###def main():
        # a, b = input().split("")
        # fun(a,b,c)
###
def func(a,b,h,m):
    result=[]
    data=[[[0 for x in range(10)] for y in range(10)] for z in range(20)]
    data[0][1][0]=make_pair(make_pair(7,11),make_pair(11,41))
    data[0][1][1]=make_pair(make_pair(13,21),make_pair(17,51))
    data[0][1][2]=make_pair(make_pair(15,52),make_pair(20,22))
    data[0][2][0]=make_pair(make_pair(5,45),make_pair(9,30))
    data[0][2][1]=make_pair(make_pair(9,15),make_pair(14,14))
    data[0][2][2]=make_pair(make_pair(12,10),make_pair(16,55))
    data[0][2][3]=make_pair(make_pair(14,45),make_pair(18,25))
    data[0][3][0]=make_pair(make_pair(5,50),make_pair(7,30))
    data[0][3][1]=make_pair(make_pair(9,0),make_pair(10,45))
    data[0][3][2]=make_pair(make_pair(14,25),make_pair(16,10))
    data[0][4][0]=make_pair(make_pair(6,10),make_pair(9,30))
    data[0][4][1]=make_pair(make_pair(10,50),make_pair(13,40))
    data[0][4][2]=make_pair(make_pair(15,30),make_pair(19,00))
    data[0][5][0]=make_pair(make_pair(5,30),make_pair(11,10))
    data[0][5][1]=make_pair(make_pair(7,20),make_pair(12,40))
    data[0][5][2]=make_pair(make_pair(15,40),make_pair(21,30))
    data[0][5][3]=make_pair(make_pair(17,10),make_pair(23,20))
    data[0][7][0]=make_pair(make_pair(5,30),make_pair(8,10))
    data[0][7][1]=make_pair(make_pair(8,10),make_pair(12,50))
    data[0][7][2]=make_pair(make_pair(12,30),make_pair(16,30))
    data[0][8][0]=make_pair(make_pair(7,30),make_pair(12,00))
    data[0][8][1]=make_pair(make_pair(16,10),make_pair(20,40))

    data[1][0][0]=make_pair(make_pair(4,30),make_pair(8,30))
    data[1][0][1]=make_pair(make_pair(8,40),make_pair(12,50))
    data[1][0][2]=make_pair(make_pair(12,30),make_pair(16,10))
    data[1][0][3]=make_pair(make_pair(17,30),make_pair(21,40))
    data[1][2][0]=make_pair(make_pair(5,1),make_pair(9,00))
    data[1][2][1]=make_pair(make_pair(7,30),make_pair(12,00))
    data[1][2][2]=make_pair(make_pair(11,30),make_pair(16,10))
    data[1][2][3]=make_pair(make_pair(15,30),make_pair(20,30))
    data[1][3][0]=make_pair(make_pair(8,20),make_pair(12,30))
    data[1][3][1]=make_pair(make_pair(11,40),make_pair(15,40))
    data[1][3][2]=make_pair(make_pair(14,20),make_pair(20,00))
    data[1][4][0]=make_pair(make_pair(5,40),make_pair(8,10))
    data[1][4][1]=make_pair(make_pair(8,10),make_pair(11,30))
    data[1][4][2]=make_pair(make_pair(12,30),make_pair(15,30))
    data[1][4][3]=make_pair(make_pair(14,50),make_pair(18,00))
    data[1][5][0]=make_pair(make_pair(6,40),make_pair(9,00))
    data[1][5][1]=make_pair(make_pair(8,30),make_pair(11,40))
    data[1][5][2]=make_pair(make_pair(12,30),make_pair(15,30))
    data[1][5][3]=make_pair(make_pair(15,30),make_pair(19,00))
    data[1][6][0]=make_pair(make_pair(6,00),make_pair(8,30))
    data[1][6][1]=make_pair(make_pair(9,30),make_pair(12,00))
    data[1][6][2]=make_pair(make_pair(13,00),make_pair(15,20))
    data[1][6][3]=make_pair(make_pair(15,30),make_pair(17,30))
    data[1][6][4]=make_pair(make_pair(18,00),make_pair(20,30))
    data[1][7][0]=make_pair(make_pair(6,30),make_pair(11,30))
    data[1][7][1]=make_pair(make_pair(12,50),make_pair(18,30))
    data[1][7][2]=make_pair(make_pair(16,40),make_pair(22,30))
    data[1][8][0]=make_pair(make_pair(5,30),make_pair(7,40))
    data[1][8][1]=make_pair(make_pair(12,40),make_pair(14,30))
    data[1][8][2]=make_pair(make_pair(17,30),make_pair(19,40))
    data[1][9][0]=make_pair(make_pair(6,00),make_pair(8,10))
    data[1][9][1]=make_pair(make_pair(12,10),make_pair(14,00))

    data[2][0][0]=make_pair(make_pair(6,00),make_pair(10,20))
    data[2][0][1]=make_pair(make_pair(9,30),make_pair(13,30))
    data[2][0][2]=make_pair(make_pair(13,00),make_pair(17,30))
    data[2][1][0]=make_pair(make_pair(6,30),make_pair(10,30))
    data[2][1][1]=make_pair(make_pair(9,50),make_pair(14,00))
    data[2][1][2]=make_pair(make_pair(13,40),make_pair(18,00))
    data[2][3][0]=make_pair(make_pair(8,30),make_pair(11,40))
    data[2][3][1]=make_pair(make_pair(12,30),make_pair(15,30))
    data[2][3][2]=make_pair(make_pair(15,30),make_pair(19,00))
    data[2][4][0]=make_pair(make_pair(6,00),make_pair(8,30))
    data[2][4][1]=make_pair(make_pair(9,30),make_pair(12,00))
    data[2][4][2]=make_pair(make_pair(13,00),make_pair(15,20))
    data[2][5][0]=make_pair(make_pair(15,30),make_pair(17,30))
    data[2][5][1]=make_pair(make_pair(18,00),make_pair(20,30))
    data[2][5][2]=make_pair(make_pair(13,00),make_pair(15,20))
    data[2][6][0]=make_pair(make_pair(15,30),make_pair(17,30))
    data[2][6][1]=make_pair(make_pair(18,00),make_pair(20,30))
    data[2][6][2]=make_pair(make_pair(12,30),make_pair(15,30))
    data[2][7][0]=make_pair(make_pair(14,50),make_pair(18,00))
    data[2][7][1]=make_pair(make_pair(6,40),make_pair(9,00))
    data[2][7][2]=make_pair(make_pair(8,30),make_pair(11,40))
    data[2][8][0]=make_pair(make_pair(12,30),make_pair(15,30))
    data[2][8][1]=make_pair(make_pair(15,30),make_pair(19,00))
    data[2][8][2]=make_pair(make_pair(6,00),make_pair(8,30))
    data[2][9][0]=make_pair(make_pair(9,30),make_pair(12,00))
    data[2][9][1]=make_pair(make_pair(13,00),make_pair(15,20))
    data[2][9][2]=make_pair(make_pair(15,30),make_pair(17,30))



    data[3][0][0]=make_pair(make_pair(13,00),make_pair(15,30))
    data[3][0][1]=make_pair(make_pair(15,30),make_pair(17,30))
    data[3][0][2]=make_pair(make_pair(18,00),make_pair(20,30))
    data[3][1][0]=make_pair(make_pair(13,30),make_pair(15,30))
    data[3][1][1]=make_pair(make_pair(14,50),make_pair(18,00))
    data[3][1][2]=make_pair(make_pair(6,40),make_pair(9,00))
    data[3][2][0]=make_pair(make_pair(8,30),make_pair(11,40))
    data[3][2][1]=make_pair(make_pair(13,30),make_pair(15,30))
    data[3][2][2]=make_pair(make_pair(15,30),make_pair(19,00))
    data[3][4][0]=make_pair(make_pair(6,00),make_pair(8,30))
    data[3][4][1]=make_pair(make_pair(9,30),make_pair(13,00))
    data[3][4][2]=make_pair(make_pair(13,00),make_pair(15,30))
    data[3][5][0]=make_pair(make_pair(15,30),make_pair(17,30))
    data[3][5][1]=make_pair(make_pair(18,00),make_pair(20,30))
    data[3][5][2]=make_pair(make_pair(13,00),make_pair(15,30))
    data[3][6][0]=make_pair(make_pair(15,30),make_pair(17,30))
    data[3][6][1]=make_pair(make_pair(18,00),make_pair(20,30))
    data[3][6][2]=make_pair(make_pair(13,30),make_pair(15,30))
    data[3][7][0]=make_pair(make_pair(14,50),make_pair(18,00))
    data[3][7][1]=make_pair(make_pair(6,40),make_pair(9,00))
    data[3][7][2]=make_pair(make_pair(8,30),make_pair(11,40))
    data[3][8][0]=make_pair(make_pair(13,30),make_pair(15,30))
    data[3][8][1]=make_pair(make_pair(15,30),make_pair(19,00))
    data[3][8][2]=make_pair(make_pair(6,00),make_pair(8,30))
    data[3][9][0]=make_pair(make_pair(9,30),make_pair(13,00))
    data[3][9][1]=make_pair(make_pair(13,00),make_pair(15,30))
    data[3][9][2]=make_pair(make_pair(15,30),make_pair(17,30))

    data[4][0][0]=make_pair(make_pair(4,30),make_pair(7,13))
    data[4][0][1]=make_pair(make_pair(9,20),make_pair(12,45))
    data[4][0][2]=make_pair(make_pair(11,00),make_pair(14,30))
    data[4][0][3]=make_pair(make_pair(17,10),make_pair(20,25))
    data[4][1][0]=make_pair(make_pair(5,15),make_pair(7,45))
    data[4][1][1]=make_pair(make_pair(8,50),make_pair(11,20))
    data[4][1][2]=make_pair(make_pair(11,20),make_pair(13,50))
    data[4][1][3]=make_pair(make_pair(18,15),make_pair(21,20))
    data[4][2][0]=make_pair(make_pair(7,55),make_pair(8,58))
    data[4][2][1]=make_pair(make_pair(11,00),make_pair(12,45))
    data[4][2][2]=make_pair(make_pair(16,45),make_pair(18,40))
    data[4][2][3]=make_pair(make_pair(19,30),make_pair(21,15))
    data[4][3][0]=make_pair(make_pair(5,30),make_pair(6,45))
    data[4][3][1]=make_pair(make_pair(7,15),make_pair(8,30))
    data[4][3][2]=make_pair(make_pair(9,30),make_pair(10,45))
    data[4][3][3]=make_pair(make_pair(11,20),make_pair(12,45))
    data[4][3][4]=make_pair(make_pair(14,30),make_pair(15,45))
    data[4][3][5]=make_pair(make_pair(19,30),make_pair(20,45))
    data[4][5][0]=make_pair(make_pair(6,00),make_pair(7,55))
    data[4][5][1]=make_pair(make_pair(8,40),make_pair(10,35))
    data[4][5][2]=make_pair(make_pair(12,5),make_pair(14,00))
    data[4][5][3]=make_pair(make_pair(16,5),make_pair(17,50))
    data[4][7][0]=make_pair(make_pair(9,30),make_pair(13,30))
    data[4][7][1]=make_pair(make_pair(11,2),make_pair(15,2))
    data[4][7][2]=make_pair(make_pair(11,17),make_pair(15,17))
    data[4][8][0]=make_pair(make_pair(12,35),make_pair(13,5))
    data[4][8][1]=make_pair(make_pair(10,30),make_pair(13,00))
    data[4][8][2]=make_pair(make_pair(14,7),make_pair(14,30))
    data[4][9][0]=make_pair(make_pair(16,30),make_pair(18,7))
    data[4][9][1]=make_pair(make_pair(10,00),make_pair(11,47))
    data[4][9][2]=make_pair(make_pair(12,30),make_pair(14,7))


    data[5][0][0]=make_pair(make_pair(4,40),make_pair(9,40))
    data[5][0][1]=make_pair(make_pair(11,30),make_pair(16,30))
    data[5][0][2]=make_pair(make_pair(18,00),make_pair(23,00))
    data[5][0][3]=make_pair(make_pair(12,45),make_pair(17,29))

DigiBoard/dboard/templates/first.html
{% extends "base_generic.html" %}

{% block content %}
<p>Welcome to Punjab Roadways!
About Us
Welcome to Punjab Roadways!
About Us
ArrowArrow
WELCOME TO PUNJAB ROADWAYS

Punjab Roadways came into being in the year 1948 with a fleet of 13 buses, which rose gradually to its highest strength of 2407 buses in the year 1985. The primary objective of Punjab Roadways is to provide an economical, reliable and comfortable transport service in the state of Punjab with connecting service to adjoining states. Punjab Roadways is also providing free/concessional travel to the deserving categories identified by the Punjab Government. Punjab Roadways is also operating and monitoring the Bus Stands of Punjab.</p>
{% endblock %}

DigiBoard/dboard/templates/index1.html
{% extends "base_generic.html" %}

{% block content %}
<br>
<br>


<h1>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;WELCOME TO PUNJAB ROADWAYS</h1>
      <br>
      <br>

<h5 style="color:black">

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Punjab Roadways came into being in the year 1948 with a fleet of 13 buses, which rose gradually to its highest strength of 2407 buses in the year 1985. The primary objective of Punjab Roadways is to provide<br><br>	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; an economical, reliable and comfortable transport service in the state of Punjab with connecting service to adjoining states. Punjab Roadways is also providing free/concessional travel to the deserving <br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;categories identified by the Punjab Government. Punjab Roadways is also operating and monitoring the Bus Stands of Punjab.This is a simple startup by my team to ensure that the people of Punjab should<br><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; get ample of comfort during their bus journey. </h5>
{% endblock %}


h1 {
	color : #000000;
	text-align : center;
	font-family: "SIMPSON";
}

DigiBoard/dboard/templates/notification_create.html
{% extends "base_generic.html" %}

{% block content %}
<p style="color:black;font-size:30px">						O FOR AMRITSAR 
	<br>						1 FOR BATHINDA 
	<br>						2 FOR CHANDIGARH 
	<br>						3 FOR JALANDHAR
	<br>						4 FOR LUDHIANA 
	<br>						5 FOR PATIALA 
	<br>						6 FOR SANGRUR 
	<br> 						7 FOR PATHANKOT
	<br> 						8 FOR FEROZEPUR 
	<br>						9 FOR MOGA</p>
<form method="POST" action="" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.media }}
	{{form.as_p}}

	<button class="btn btn-success" type="submit">Yup!Done</button>
</form>



{% endblock %}

DigiBoard/dboard/templates/search.html
{% extends "base_generic.html" %}
{% block headfile %}
    <link href="https://fonts.googleapis.com/css?family=Germania+One" rel="stylesheet">
    <style>
        body, html {
            height: 100%;
            width: 100%;
        }

        .bg {
            /* The image used */

            /* Full height */
            height: 100%;

            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: 100% 100%;
        }
    </style>


{% load static %}
{% endblock %}
{% block content %}
{% for each in search_list %}
    



<div class="col-sm-12">
      
<div class="card card-inverse" style="background-color: #e8e4d7; border-color: #333; margin-bottom: 40px;">
  <div class="card-block col-sm-12">

    <h3 class="card-title" style="color: #000"> <font size="45px"><a href=">{{ each.heading }}</a></font> <small style="font-size: 15px"><a href="#"> {{each.user}}</a></small> <small style="font-size: 10px">{{ each.timestamp | timesince}} ago</small></h3>
    {% if each.xm is not -1 %}
    <p style="color:black;font-size: 20px">Start Location:{{each.source}}</p>
    <p style="color:black;font-size: 20px">End Location:{{each.des}} </p>
    <p style="color:black;font-size: 20px">Departure Time: {{each.HH}}:{{each.MM}}</p>
    <p style="color:black;font-size: 20px;">YOU CAN REACH DESTINATION AT : {{each.am}}:{{each.bm}}<br>AND TOTAL COST CONSIDERING Rs. 1.5 PER MIN WOULD BE APPROXIMATELY=Rs. {{each.cm}}<br>
    OR YOU CAN GET A DIRECT BUS AT = {{each.dm}}:{{each.em}} AND REACH BY- {{each.fm}}: {{each.gm}}
            </p>
    {% else %}
    <p>NO DIRECT BUS AVAILABLE</p>
    {% endif %}
      <!-- <a href="#" class="btn btn-primary">Read More</a> -->
    </div>
  </div>
</div>
{% endfor %}




<hr>
{% if is_paginated %}

        <div style="">
            <center>
                {% if page_obj.has_previous %}
                    <a href="/?page={{ page_obj.previous_page_number }}"><<</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/?page={{ page_obj.next_page_number }}">>></a>
                {% endif %}
          </center>
        </div>
    
{% endif %}
<hr>

{% endblock %}

DigiBoard/dboard/templates/signup.html
{% extends 'base_generic.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
  {{form.as_p}}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}